# Generated by Django 4.0.6 on 2022-07-29 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('contributor', models.ManyToManyField(related_name='project_contributor', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('priority', models.CharField(max_length=50, verbose_name='Priorité')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('contributor', models.ManyToManyField(related_name='issue_contributor', to=settings.AUTH_USER_MODEL, verbose_name='Contributeur')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.projects', verbose_name='Projet')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.issues', verbose_name='Probleme')),
            ],
        ),
    ]
