# Generated by Django 4.0.6 on 2022-08-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='contributor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='contributor',
            new_name='user',
        ),
    ]
