# Generated by Django 4.0.6 on 2022-08-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_contributor_issues_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='user',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='contributor',
        ),
    ]
